spring.application.name=projectZ

spring.datasource.url=jdbc:mysql://localhost:3306/projectZ
spring.datasource.username=root
spring.datasource.password=shahid123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

security_key=skjd9834ksldfj3498u3rnkdfjk342985knfjdksjdfksd

